seed: 42 # random seed

model: resnet34 # Should be in ["resnet18", "resnet34", "resnet50"]

dataset: cifar-10 # Should be in ["cifar-10", "cifar-100"]
data_root: data # Directory of the data
validation_ration: 0.1 # Ratio to split the training set to get the validation set

batch_size: 128
eval_batch_size: 32 # Test batch size
num_epochs: 200 # Training epochs

lr: 0.1 # Learning rate
momentum: 0.9 # Momentum in SGD optimizer
weight_decay: 5e-4 # L2 regularization

# data split
clean_ratio: 0.4 # 0.4 * 50000 = 20000 - Keep clean_ratio of the training data clean and add noise to the rest
train_ratio: 0.5 # 0.5 * 20000 = 10000 - The ratio of training set in clean data, the rest is calibration set

# lr_scheduler
lr_decay_factor: 0.1 # Factor of learning rate decay, gamma in StepLR
lr_decay_epochs: 160 # The period to decay learning rate

# run name to save
name: default # Run name

# load checkpoint
skip_first_training: store_true # Skip training on the clean set
load_path: None # Run path to load checkpoint from